### PR TITLE
Updating pybind11 dependecy version to resolve a compilation issue

### PR DESCRIPTION
**Pull request by whaeck**
@cjosey This should resolve that compilation issue you mentioned.

### CODE REVIEW

**Comment by cjosey** [comment]
It does not resolve GCC 13 (I think because one of the dependencies added `-Werror` -- this is why `-Werror` should never be in production because warnings change with time), but it does resolve LLVM 16.

**Review by cjosey — DISMISSED** [review]

**Comment by whaeck** [comment]
I didn't know there was a gcc 13 issue. What exactly is it?

**Comment by cjosey** [comment]
```
In file included from [...]/ACEtk/buildgcc/_deps/range-v3-src/include/range/v3/range_fwd.hpp:20,
                 from [...]/ACEtk/buildgcc/_deps/range-v3-src/include/range/v3/view/any_view.hpp:22,
                 from [...]/ACEtk/python/src/views.hpp:10,
                 from [...]/ACEtk/python/src/ACEtk.python.cpp:6:
[...]/ACEtk/buildgcc/_deps/range-v3-src/include/meta/meta.hpp:3190:19: error: declaration of 'template<class Fn> template<class State, class A> using meta::detail::partition_<Fn>::invoke = meta::_t<meta::detail::partition_<Fn>::impl<State, A> >' changes meaning of 'invoke' [-Wchanges-meaning]
 3190 |             using invoke = _t<impl<State, A>>;
      |                   ^~~~~~
[...]/ACEtk/buildgcc/_deps/range-v3-src/include/meta/meta.hpp:3185:34: note: used here to mean 'using meta::invoke = typename Fn::invoke<A>'
 3185 |                 using type = if_<invoke<Fn, A>, pair<list<Yes..., A>, list<No...>>,
      |                                  ^~~~~~~~~~~~~
[...]/ACEtk/buildgcc/_deps/range-v3-src/include/meta/meta.hpp:541:11: note: declared here
  541 |     using invoke = typename Fn::template invoke<Args...>;
      |           ^~~~~~
make[2]: *** [CMakeFiles/ACEtk.python.dir/python/src/ACEtk.python.cpp.o] Error 1
make[1]: *** [CMakeFiles/ACEtk.python.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by whaeck** [comment]
Ugh. I hate it when that happens. We were planning on ripping out ranges to enable intel support, so ...

**Review by cjosey — APPROVED** [review]

**Pull request merged**
